# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
